### ISSUE TITLE
Unable to initialize/start application

### ISSUE THREAD

**Issue by ddziubanski** [docusign/Lobby-App#5]
Express server listening on port 3000

Error: /home/it/lobby/views/includes/js/center.jade:4
    2|
    3|   jQuery.fn.center = function() {
  > 4|     this.css('position', 'absolute');
    5|     this.css('top', Math.max(0, (($(window).height() - this.outerHeight()) / 2) + $(window).scrollTop()) + "px");
    6|     this.css('left', Math.max(0, (($(window).width() - this.outerWidth()) / 2) + $(window).scrollLeft()) + "px");
    7|     return this;

unexpected text ;

    at Object.Lexer.fail (/home/it/lobby/node_modules/jade/lib/lexer.js:887:11)
    at Object.Lexer.next (/home/it/lobby/node_modules/jade/lib/lexer.js:947:15)
    at Object.Lexer.lookahead (/home/it/lobby/node_modules/jade/lib/lexer.js:113:46)
    at Parser.lookahead (/home/it/lobby/node_modules/jade/lib/parser.js:102:23)
    at Parser.peek (/home/it/lobby/node_modules/jade/lib/parser.js:79:17)
    at Parser.tag (/home/it/lobby/node_modules/jade/lib/parser.js:773:22)
    at Parser.parseTag (/home/it/lobby/node_modules/jade/lib/parser.js:759:17)
    at Parser.parseExpr (/home/it/lobby/node_modules/jade/lib/parser.js:211:21)
    at Parser.block (/home/it/lobby/node_modules/jade/lib/parser.js:729:25)
    at Parser.tag (/home/it/lobby/node_modules/jade/lib/parser.js:838:24)
GET / 500 1280ms
Any Tips would be great.

**Comment by shijun** [comment]
The Jade syntax has to be updated to account for client-side JS.

See here for more details:
https://stackoverflow.com/questions/22524986/node-js-jade-syntax-error-unexpected-token

**Comment by ddziubanski** [comment]
Thanks TImothy,

I ended up going back a version on node, and things whirled into action.

Only issue im having is making database changes from the web interface, as
i get a 403 denied error on the console...

Simple fix?
